spring:
  application:
    name: java-backend-starter
  datasource:
    url: jdbc:mysql://localhost:3306/zhida
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 123456
springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    enabled: false
mybatis-flex:
  configuration:
    # 方便开发阶段排查问题的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # Mapper XML 文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
jwt:
  secret: 4ryT+67BFbvVl6HqMFzdOlMcaVUcCrf3hwPjTN4Qmog=
  issuer: zhida
oss:
  uri: http://localhost:9000
  access-key: jO48DZ09s65NhtvWYxub
  secret-key: Y5Oa1HvSyRJz8sZ7jcMACQTbtfNhgemFK0VwWnxi
  public-bucket: zhida-public
  private-bucket: zhida-private